In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install pyreadr

Collecting pyreadr
  Downloading pyreadr-0.5.6-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.3 kB)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from pyreadr) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadr) (1.17.0)
Downloading pyreadr-0.5.6-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (788 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 788.3/788.3 kB 16.8 MB/s eta 0:00:00
Installing collected packages: pyreadr
Successfully installed pyreadr-0.5.6

In [ ]:
import os

for f in os.listdir('/content/drive/MyDrive'):
    print(f)

Colab Notebooks
onam
do.gsheet
FormSeven_copy.pdf
Document from Adwaith
Document from Adwaith.pdf
Copy of D1S4A2 -Part 1-Creating Toys Using Low Cost_ No Cost Materials and Resources (1).mp4
Copy of D1S2A2 - Sensitive Periods for Child Development (Hindi) (1).mp4
Copy of D1S4A1 - TLM FOR ANGANWADI (1).mp4
Copy of D1S4A2 - Part 2- Creating Toys Using Low Cost_ No Cost Materials and Resources_ 2 (1).mp4.mp4
Copy of D1S1A1 - PBPB Launch Video (1).mp4
Copy of D1S4A1 - TLM FOR ANGANWADI.mp4
Copy of D1S4A2 - Part 2- Creating Toys Using Low Cost_ No Cost Materials and Resources_ 2.mp4.mp4
Copy of D1S4A2 -Part 1-Creating Toys Using Low Cost_ No Cost Materials and Resources.mp4
Copy of D1S1A1 - PBPB Launch Video.mp4
Copy of D1S2A2 - Sensitive Periods for Child Development (Hindi).mp4
Assignment3.pdf
Assignment2.pdf
Assignment1.pdf
iris_visdrone_tuning

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving dataset_rds.zip to dataset_rds.zip

In [ ]:
!unzip -q dataset_rds.zip -d /content/studentlife

In [ ]:
import os

for root, dirs, files in os.walk("/content/studentlife"):
    print(root)
    for f in files[:5]:
        print("   ", f)

/content/studentlife
/content/studentlife/dataset_rds
/content/studentlife/dataset_rds/sensing
    bluetooth.Rds
    phonecharge.Rds
    wifi_location.Rds
    activity.Rds
    dark.Rds
/content/studentlife/dataset_rds/survey
    FlourishingScale.Rds
    BigFive.Rds
    LonelinessScale.Rds
    PHQ-9.Rds
    panas.Rds
/content/studentlife/dataset_rds/EMA
    PAM.Rds
    Class 2.Rds
    Green Key 2.Rds
    Dining Halls.Rds
    QR_Code.Rds
/content/studentlife/dataset_rds/other
    app_usage.Rds
    calendar.Rds
    call_log.Rds
    dining.Rds
    sms.Rds

In [ ]:
!pip install -q pyreadr

In [ ]:
BASE = "/content/studentlife/dataset_rds"

In [ ]:
import pyreadr

phq = pyreadr.read_r(
    f"{BASE}/survey/PHQ-9.Rds"
)[None]

print(phq.shape)
print(phq.columns)
phq.tail()

(84, 12)
Index(['uid', 'type', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9',
       'Q10'],
      dtype='object')

,uid,type,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10
79,52,post,Several days,Nearly every day,Nearly every day,More than half the days,Nearly every day,Several days,Not at all,Several days,Several days,Extremely difficult
80,53,post,Not at all,Several days,Nearly every day,More than half the days,Nearly every day,Not at all,More than half the days,Not at all,Not at all,Somewhat difficult
81,56,post,Not at all,Not at all,Not at all,More than half the days,Not at all,Not at all,Several days,Not at all,Not at all,Somewhat difficult
82,58,post,Not at all,Several days,Not at all,More than half the days,More than half the days,Several days,Several days,Several days,Not at all,Not difficult at all
83,59,post,Not at all,Not at all,More than half the days,More than half the days,Several days,Not at all,Several days,Several days,Not at all,Somewhat difficult

In [ ]:
stress = pyreadr.read_r(
    f"{BASE}/EMA/Stress.Rds"
)[None]

print(stress.shape)
print(stress.columns)
stress.head()

(2017, 3)
Index(['null', 'timestamp', 'uid'], dtype='object')

                       null     timestamp uid
0  43.75908069,-72.32885314  1.364114e+09   0
1  43.75908069,-72.32885314  1.364114e+09   0
2  43.70677151,-72.28746626  1.364178e+09   0
3                         1  1.364170e+09   0
4                         1  1.364178e+09   0

In [ ]:
mood = pyreadr.read_r(
    f"{BASE}/EMA/Mood.Rds"
)[None]

print(mood.shape)
print(mood.columns)
mood.head()

(277, 7)
Index(['happy', 'happyornot', 'location', 'timestamp', 'sad', 'sadornot',
       'uid'],
      dtype='object')

   happy happyornot                  location     timestamp  sad sadornot uid
0    1.0          2  43.75921839,-72.32919741  1.366870e+09  3.0        1   0
1    2.0          1                   Unknown  1.366858e+09  4.0        1   0
2    2.0          1  43.71332016,-72.30876457  1.368719e+09  1.0        1   0
3    3.0          1  43.75880824,-72.32925862  1.368631e+09  1.0        2   0
4    2.0          1  43.75929012,-72.32904032  1.368803e+09  1.0     null   0

In [ ]:
sleep = pyreadr.read_r(
    f"{BASE}/EMA/Sleep.Rds"
)[None]

print(sleep.shape)
print(sleep.columns)
sleep.head()

(1644, 6)
Index(['hour', 'location', 'rate', 'timestamp', 'social', 'uid'], dtype='object')

   hour location  rate     timestamp  social uid
0   NaN      NaN   NaN  1.364115e+09     NaN   0
1   NaN      NaN   NaN  1.364115e+09     NaN   0
2   NaN      NaN   NaN  1.364114e+09     NaN   0
3   NaN      NaN   NaN  1.364115e+09     NaN   0
4   NaN      NaN   NaN  1.364114e+09     NaN   0

In [ ]:
activity = pyreadr.read_r(
    f"{BASE}/sensing/activity.Rds"
)[None]

print(activity.shape)
print(activity.columns)
activity.head()

(22842191, 3)
Index(['timestamp', 'activity_inference', 'uid'], dtype='object')

      timestamp  activity_inference uid
0  1.364357e+09                 0.0   0
1  1.364357e+09                 0.0   0
2  1.364357e+09                 0.0   0
3  1.364357e+09                 0.0   0
4  1.364357e+09                 0.0   0

In [ ]:
import pandas as pd

activity["datetime"] = pd.to_datetime(
    activity["timestamp"],
    unit="s"
)

activity["date"] = activity["datetime"].dt.date

activity.head()

      timestamp  activity_inference uid            datetime        date
0  1.364357e+09                 0.0   0 2013-03-27 04:00:01  2013-03-27
1  1.364357e+09                 0.0   0 2013-03-27 04:00:04  2013-03-27
2  1.364357e+09                 0.0   0 2013-03-27 04:00:07  2013-03-27
3  1.364357e+09                 0.0   0 2013-03-27 04:00:09  2013-03-27
4  1.364357e+09                 0.0   0 2013-03-27 04:03:12  2013-03-27

In [ ]:
daily_activity = (
    activity
    .groupby(
        ["uid", "date", "activity_inference"]
    )
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

daily_activity.head()

/tmp/ipykernel_2149/3595353432.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(

activity_inference uid        date   0.0  1.0  2.0  3.0
0                    0  2013-03-27  5398  731  309  202
1                    0  2013-03-28  6949  382  173  130
2                    0  2013-03-29  6682  912  104  274
3                    0  2013-03-30  4144  354   32  149
4                    0  2013-03-31  6470  725  612  197